### ISSUE TITLE
How to generate ViewComponent previews for entire project

### ISSUE THREAD

**Issue by zachfeldman** [lookbook-hq/lookbook#107]
Hi, thanks for this great library it looks awesome!

I wanted to try using this in our Rails 6.1.6 app and installed the gem/followed the instructions to mount the routes, but when I navigate to the page I don't see any components:
![Screenshot from 2022-06-29 10-54-23](https://user-images.githubusercontent.com/1437644/176468107-c31c91b8-48a5-40e8-b136-198e4e459e4f.png)

I realized this is because we have nothing in the `app/components/previews` folder as described here:
https://viewcomponent.org/guide/previews.html

I found a generator for previews here https://viewcomponent.org/guide/generators.html#generate-a-preview but I was wondering if anyone here knows of a command to just auto-generate previews from a ton of pre-existing view components. Otherwise I'll be doing a lot of manual work by hand to be able to try this at our company.

I appreciate any suggestions and thank you for your time!

**Comment by allmarkedup** [comment]
Hey @zachfeldman - I'm afraid nothing like that currently exists as far as I'm aware, sorry 😕

You could try asking over on the ViewComponent repo issues or discussions as there may be people there who have looked into at least generating skeleton Preview files for a bunch of existing components, but I haven't stumbled across something like that myself yet.

Sorry I can't be of more help right now!
