### ISSUE TITLE
Order of Content and Named Slot Bug

### ISSUE THREAD

**Issue by anthonyshchang** [lookbook-hq/lookbook#299]
> **Before opening an issue** please make sure you have consulted the [Lookbook documentation](https://lookbook.build) (in particular the [Troubleshooting section](https://lookbook.build/guide/troubleshooting/)) and have checked the existing issues to see if this has already been reported.

### Describe the bug

When rendering a component that has a named slot (hereinafter `named_slot`), the generic `content` slot is empty if its content is placed before the block for the `named_slot`, but will be present if placed after.

### To Reproduce

my_component.rb
```
class MyComponent
  renders_one :prefix
end
```

my_component.html.erb
```
<div>
  <%- if prefix %>
    <%= prefix %>
  <%- end %>
  <%= content %>
</div>
```

```
class MyComponentPreview
  def renders_with_prefix_but_no_content
    render(MyComponent.new) do |component|
      "content"
      component.prefix { "prefix" }
    end
  end
  
  def renders_with_prefix_and_content
    render(MyComponent.new) do |component|
      component.prefix { "prefix" }
      "content"
    end
  end
end
```

### Expected behavior

Component renders with both `content` and `prefix` slots, regardless of the order they are provided to the component.

### Version numbers 

Please complete the following information:

* Lookbook: 1.4.5
* ViewComponent: 2.75.0
* Rails: Rails 7.0.4
* Ruby: ruby 3.1.2p20

**Comment by Spone** [comment]
Hi @anthonyshchang, thanks for opening an issue. It's actually not a bug with Lookbook but rather the way `content` is implemented in ViewComponent. The content is the return value of the block passed when rendering the component, so if you pass a slot *after* the content, it will not work.

Alternatively, you can use `with_content` to pass the content directly, without messing with the slots. See https://viewcomponent.org/guide/getting-started.html#with_content
